### PR TITLE
Updated gradle to version 2.4 and maven URL

### PR DESCRIPTION
**Pull request by halvors**
Updated gradle to version 2.4 and maven URL from maven.magik6k.net to maven.novaapi.net.

### CODE REVIEW

**Comment by RX14** [comment]
Well the two URLs point to the same place right now... On the other hand that might change in the future.

**Comment by halvors** [comment]
Ok. I thought maybe that was the case. Yeah i don't see why not to use the "maven.novapi.net" URL since it's also the one that is used by NovaCore and NovaWrapper.

**Comment by RX14** [comment]
And that's why I accepted your PR

**Comment by halvors** [comment]
:+1:

**Pull request merged**
