### PR TITLE
Updated sample to match the wrapper sample

### PR DESCRIPTION
**Pull request by Mitchellbrine**
This is what I could tell needed to be changed to be similar to the MC wrapper's sample.

(If this is incorrect, just close it. I don't care. This PR was just to keep it up to date with your other sample)

### CODE REVIEW

**Comment by asiekierka** [comment]
Gifts! I see you're learning our APIs. Any opinions?

**Comment by Mitchellbrine** [comment]
It looks simpler than Forge, easy to read. The concept is incredible and when it becomes released, this will be amazing. I have two concerns. There are very few popular voxel games that use Java. I can't think of any besides Minecraft. I can think of a bit that use C++, C# or Lua, but not much in Java. Also, it appears you're compiling in Java 1.8 (at least using features of it), so backwards compatibility wouldn't work. Just a concern. Java 8 is starting to be used a lot more, so I see it's a viable option to compile in. Anyway, other than that, this concept, idea, and the way you're doing it looks great!

**Comment by asiekierka** [comment]
@Mitchellbrine - We know. Terasology is one which uses Java, also Starmade.

The reason we're using Java is to make it easy for existing mods to jump ship. Also, there is at least one engine being planned with NOVA in mind specifically.

**Comment by Mitchellbrine** [comment]
Interesting, I didn't know those games were written in Java. Especially Starmade.

Yeah, I know using Java makes it easier on the previous modder to migrate. My concern was on 1.8 and how it wasn't fully integrated into all systems. It would abandon a bit of the community and, while not the majority, it's something to think about.

Also, I did notice how NOVA could be planned around when making a game engine. It looks very easy-to-use and keep in mind and I'd like to see that engine when it's done.

Anyways, NOVA has a lot of potential and I look forward to using it in the future.

**Comment by Mitchellbrine** [comment]
Closing this PR and moving to another one because I had issues with merge conflicts and might've accidentally deleted my fork.

**Pull request closed without merging**
